#!/bin/bash

declare -r SCRIPT="$([[ $0 = /* ]] && echo "$0" || echo "$PWD/${0#./}")"
declare -r BASE_DIR="$(dirname $SCRIPT)"

declare -r RED="$(tput setaf 1)"
declare -r GREEN="$(tput setaf 2)"
declare -r NORMAL="$(tput sgr0)"

function log {
    echo "${RED}#${GREEN} ${1}${NORMAL}"
}

function reorder_patches {
    local -r PATCH_DIR="$1" ; shift

    log "Reordering patches in $PATCH_DIR"

    cd "$BASE_DIR/$PATCH_DIR"

    local -i NUM=1
    for NAME in *; do
        NAME_WITHOUT="${NAME:4}"
        OLD_NUM="${NAME::4}"
        NEW_NUM="$(printf "%04d" ${NUM})"
        NEW_NAME="${NEW_NUM}${NAME_WITHOUT}"
        if [[ "$NEW_NAME" != "$NAME" ]]; then
            echo "(${OLD_NUM} -> ${NEW_NUM})${NAME_WITHOUT}"
            mv "$NAME" "${NEW_NAME}"
        fi
        NUM="$((NUM + 1))"
    done
}

reorder_patches Patches-01-Connection-Emerge
reorder_patches Patches-02-Eliralin
