#!/bin/bash

declare -r SCRIPT="$([[ $0 = /* ]] && echo "$0" || echo "$PWD/${0#./}")"
declare -r BASE_DIR="$(dirname $SCRIPT)"

function update {
    local -r ORIGIN="$1"            ; shift
    local -r ORIGIN_BRANCH="$1"     ; shift
    local -r UPSTREAM="$1"          ; shift
    local -r UPSTREAM_BRANCH="$1"   ; shift
    local -r FIXED_COMMIT="$1"      ; shift

    cd "$BASE_DIR/$ORIGIN"
    git fetch "$UPSTREAM"
    git checkout -B "$ORIGIN_BRANCH" --track "$UPSTREAM/$UPSTREAM_BRANCH"
    if [[ "$FIXED_COMMIT" ]]; then
        git reset --hard "$FIXED_COMMIT"
    fi
}

# The f8e1b4e68cb48a3af399c27604c8cc106958f02b is to fix commit to not merge the latest changes
update Refresh-origin master origin python3.4 # f8e1b4e68cb48a3af399c27604c8cc106958f02b
