#!/bin/bash

declare -r SCRIPT="$([[ $0 = /* ]] && echo "$0" || echo "$PWD/${0#./}")"
declare -r BASE_DIR="$(dirname $SCRIPT)"

function update {
    local -r ORIGIN="$1"            ; shift
    local -r ORIGIN_BRANCH="$1"     ; shift
    local -r UPSTREAM="$1"          ; shift
    local -r UPSTREAM_BRANCH="$1"   ; shift

    cd "$BASE_DIR/$ORIGIN"
    git fetch "$UPSTREAM"
    git checkout -B "$ORIGIN_BRANCH" --track "$UPSTREAM/$UPSTREAM_BRANCH"
}

update Refresh master origin python3.4
# This is just a small hack to not merge the latest changes
cd "$BASE_DIR/Refresh"
git reset --hard f1ed6f0174cae37de2c1051592667123cf7eba77
